### ISSUE TITLE
[BUG] Parsing module exports same parsed_result about all modules.

### ISSUE THREAD

**Issue by e7217** [Marker-Inc-Korea/AutoRAG#1064]
**Describe the bug**

Hello,

Could you help me? It seems that there has been a change in the parsing module.
The parsing module now exports the same `parsed_result` for all modules.
I have set up my config file for the parser as shown below:
```yaml
  - module_type: langchain_parse
    parse_method: upstagedocumentparse
    split: [ page ]
    file_type: pdf
    output_format: [ html, markdown ]
  - module_type: llamaparse
    result_type: markdown
    file_type: pdf
    language: ko
```
The current parsed result is as follows:

![Image](https://github.com/user-attachments/assets/ff7b9242-6a4c-41c4-ba39-c1bdd5108799)

However, the previous results were different. For example, when I set the `output_format` to `html` in `upstagedocumentparse`, the parsed result used to contain HTML tags.

![Image](https://github.com/user-attachments/assets/87fc55d7-eee1-4f32-8893-3837fad6e512)

I would appreciate your assistance. Thank you.
