### ISSUE TITLE
[BUG] When `file_type` is set to `all_files`, only `pdfminer` is used

### ISSUE THREAD

**Issue by e7217** [Marker-Inc-Korea/AutoRAG#1065]
**Describe the bug**
Hello,

It seems that when the parser module is configured with `file_type: all_files`, only pdfminer is applied. I have tried using `langchain_parser/upstagedocumentparse` and `llamaparser`, and both appear to use pdfminer exclusively. Even when I set the `output_format` to `html`, it seems like pdfminer is still being used. Am I mistaken about something?

Below is the YAML file I configured:
```yaml
- module_type: langchain_parse
  parse_method: upstagedocumentparse
  split: page
  file_type: all_files
  output_format: html
```
or
```yaml
- module_type: llamaparse
  result_type: markdown
  file_type: all_files
  language: ko
```

And here is the result:
![Image](https://github.com/user-attachments/assets/6f2a893b-74ba-484b-b77d-40790c8adf98)

I would appreciate your help. Thank you.
