### ISSUE TITLE
[Feature Request] Running locally

### ISSUE THREAD

**Issue by AlbertoMQ** [Marker-Inc-Korea/AutoRAG#1076]
Finding no resources on how to run this all locally. 

Getting a timeout error, looks like from open_ai

Guessing it's defaulting to open_ai if it doesn't find the llm? Not really sure

Here is my YAML

```yaml
node_lines:
- node_line_name: retrieve_node_line
  nodes:
  llm_model:
  type: huggingface
  model_name: HuggingFaceH4/zephyr-7b-beta 

  
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_ndcg, retrieval_mrr]  # Include multiple metrics for comparison
      top_k: 5  # Adjust based on desired recall depth
      modules:
        - module_type: vectordb
          vectordb: default  # Default vector database used for retrieval
          embedding_model:
            type: huggingface
            model_name: sentence-transformers/all-MiniLM-L6-v2  # Model 1
```

output

[01/27/25 12:21:13] INFO     [posthog.py:22] >> Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry posthog.py:22
                             for more information.                                                                                                      
[01/27/25 12:21:14] INFO     [_base_client.py:1666] >> Retrying request to /embeddings in 0.479268 seconds                          _base_client.py:1666
                    INFO     [_base_client.py:1666] >> Retrying request to /embeddings in 0.892558 seconds                          _base_client.py:1666
[01/27/25 12:21:15] INFO     [_base_client.py:1666] >> Retrying request to /embeddings in 1.674951 seconds                          _base_client.py:1666
[01/27/25 12:21:17] INFO     [_base_client.py:1666] >> Retrying request to /embeddings in 3.469390 seconds                          _base_client.py:1666
Ingesting VectorDB... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/1 0:00:49
