### ISSUE TITLE
[BUG] Custom embedding models

### ISSUE THREAD

**Issue by AlbertoMQ** [Marker-Inc-Korea/AutoRAG#1081]
Thank you for making this and for your help.

I am having a near impossible time setting up custom embedding models. 
Here are things I've tried

```python
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
embed_model_name = Config._default_embed_model_name.replace("/", "-")
embed_model = HuggingFaceEmbedding(
                    model_name= "BAAI/bge-large-en",
                    cache_folder=   Config.MODELS_DIR
                )
autorag.embedding_models[embed_model_name] = LazyInit(Config.default_embed_model, model_name=Config._default_embed_model_name)
autorag.embedding_models[embed_model_name] = Config.default_embed_model
```

```yaml
vectordb:
  - name: bge-large
    db_type: chroma
    client_type: persistent
    embedding_model: BAAI-bge-large-en
    collection_name: BAAI-bge-large-en
    path: ${PROJECT_DIR}/data/chroma
node_lines:
- node_line_name: retrieve_node_line
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision,
                  retrieval_map, retrieval_mrr, retrieval_ndcg]
      top_k: [1, 3, 5, 10, 50]
      modules:
        - module_type: vectordb
          vectordb: bge-large
```

///////////////////////////////////

                             TypeError: missing a required argument: 'nodes'          

//////////////////////////////////

Switching embeddings                              
  embedding_model:
  - type: huggingface
    model_name: intfloat/multilingual-e5-large-instruct         

///////////////////////////
This gives an error because it is called as embedding_models[] in the code, and this dict won't do.
//////////////////////////

I've tried this style as well.  (I have no idea which I'm supposed to use)

      modules:
        - module_type: vectordb
          embedding_model:
           - bge-large-en

**Comment by vkehfdl1** [comment]
1. Upgrade AutoRAG version to latest (up to v0.3.13)
2. Try like this.

```yaml
vectordb:
- name: bge-large
  db_type: chroma
  client_type: persistent
  path: ${PROJECT_DIR}/data/chroma
  embedding_model:
  - type: huggingface
    model_name: BAAI/bge-large-en
```

And you can use the "bge-large" vectordb at the retrieval node.
