### ISSUE TITLE
How to use the Custom embedding?

### ISSUE THREAD

**Issue by girlsending0** [Marker-Inc-Korea/AutoRAG#1087]
Hello, 
Thank you for taking a trouble. 

I want to use the sentence transformer custom embedding, so I tried to configure the main and yaml file. 
I refer to [documentaion](https://medium.com/@autorag/making-benchmark-of-different-embedding-models-1c327a0dae1f), and write the code below;

`main.py`
```
import autorag
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

if not hasattr(autorag, "embedding_models"):
    autorag.embedding_models = {}

# 🔹 기존 embedding_models에 추가
autorag.embedding_models["math_embedding"] = autorag.LazyInit(
    HuggingFaceEmbedding,
    model_name="sentence-transformers/math-similarity/Bert-MLM_arXiv-MP-class_zbMath",
)


def main(config, qa_data_path, corpus_data_path, project_dir):
    load_dotenv()

    if os.getenv("OPENAI_API_KEY") is None:
        raise ValueError("OPENAI_API_KEY environment variable is not set")
    if not os.path.exists(project_dir):
        os.makedirs(project_dir)
    evaluator = Evaluator(qa_data_path, corpus_data_path, project_dir=project_dir)
    evaluator.start_trial(config)

```

`test.yaml`

```
node_lines:
- node_line_name: retrieve_math_node_line
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_ndcg, retrieval_map]
      top_k: 3
      modules:
        # - module_type: bm25
        #   bm25_tokenizer: [ ko_kiwi, ko_okt, ko_kkma ]
        - module_type: vectordb
          embedding_model: math_embedding
          # - type: huggingface
          #   model_name: intfloat/multilingual-e5-large-instruct
        # - module_type: vectordb
        #   embedding_model: math_embedding
```

when I check the log, the `openai embedding` was still used.

![Image](https://github.com/user-attachments/assets/332a4d58-2aab-4077-b489-8722eb94bbb5)

when I change the hugging face embedding (bge-m3, etc.), only openai embedding was loaded.
how to change the custom embedding?

and second, Is there any way to utilize already computed embeddings by any chance?

Thank you. 😄
