### ISSUE TITLE
[Question]: OpenAILike with custom OPENAI_API_BASE

### ISSUE THREAD

**Issue by omar-araboghli** [Marker-Inc-Korea/AutoRAG#284]
Hi, 

is it possible to use custom LLMs hosted privately through the `OpenAILike` object of LlamaIndex with a custom `OPENAI_API_BASE` ? 

I saw the possibility of defining `openailike` in [the docs](https://marker-inc-korea.github.io/AutoRAG/local_model.html#supporting-llm-models) but with no further information regarding the private host.

Thanks! :)

**Comment by vkehfdl1** [comment]
@omar-araboghli 
Of course you can. You can put any parameters from LlamaIndex `OpenAILike` LLM class. [LlamaIndex Docs](https://docs.llamaindex.ai/en/v0.9.48/api_reference/llms/openai_like.html)

```
nodes:
  - node_line_name: node_line_1
    nodes:
      - node_type: generator
        modules:
          - module_type: llama_index_llm
            llm: openailike
            model: mistralai/Mistral-7B-Instruct-v0.2
            api_base: your_api_base
            api_key: your_api_key
```
