### ISSUE TITLE
[HotFix] Add CNAME file for custom docs domain

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#490]

**Comment by vkehfdl1** [comment]
To use a custom domain with GitHub Pages and ensure that your custom domain settings are preserved during deployment, you need to include a `CNAME` file in the `docs/build/html` directory. This file should contain your custom domain name.

Here's how you can modify your GitHub Actions workflow to include the `CNAME` file:

1. **Create a `CNAME` file**: Add a `CNAME` file in your `docs/source` directory (or wherever your source files are) with your custom domain name. For example, if your custom domain is `www.example.com`, the `CNAME` file should contain:

    ```
    www.example.com
    ```

2. **Ensure the `CNAME` file is copied to the build directory**: Modify your `sphinx-build` command to ensure the `CNAME` file is included in the `docs/build/html` directory.

3. **Update your GitHub Actions workflow**: Add a step to copy the `CNAME` file to the `docs/build/html` directory before deploying.

Here's the updated YAML file:

```yaml
name: Sphinx build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upgrade pip
      run: | 
        python -m pip install --upgrade pip
    - name: Install gcc
      run: |
        sudo apt-get install gcc
    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
    - name: Build HTML
      run: |
        sphinx-build -b html docs/source docs/build/html
    - name: Copy CNAME
      run: |
        cp docs/source/CNAME docs/build/html/CNAME
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
```

### Explanation:

- **Create a `CNAME` file**: Ensure you have a `CNAME` file in your `docs/source` directory with your custom domain name.
- **Copy the `CNAME` file**: The `Copy CNAME` step ensures that the `CNAME` file is included in the `docs/build/html` directory.
- **Deploy**: The `peaceiris/actions-gh-pages@v3` action will now deploy the contents of `docs/build/html` to GitHub Pages, including the `CNAME` file, which will preserve your custom domain settings.

This should fix the issue of your URL reverting to the `github.io` domain.

Citations:
