### ISSUE TITLE
vLLM terminated unexpectedly at the multi-gpu environment

### ISSUE THREAD

**Issue by gnekt** [Marker-Inc-Korea/AutoRAG#512]
Hello,

While using the ELI5 and TriviaQA datasets from the Hugging Face library, I encountered errors related to missing documents that are not present in the corpus. I experienced a similar issue with the HotpotQA dataset but managed to resolve it by cleaning the mismatched documents.

However, when I switched to using the HotpotQA dataset, I observed some strange behavior with the VLLM module. Specifically, the process is terminated without any error messages.

Thank you in advance.

**Comment by vkehfdl1** [comment]
Hello @gnekt First of all, Thanks for the report.
We'll check Eli5 and triviaQA dataset first. @bwook00 @Eastsidegunn will help this also.

And about the termination of vLLM module. It can be OOM error. Do you check your VRAM status? 
And what file did you use, and what system you used for running each dataset?

**Comment by CristianCosci** [comment]
> And what file did you use, and what system you used for running each dataset?

CPU: AMD EPYC 7402P (48) @ 2.800GHz 
GPU0: NVIDIA GeForce RTX 3090 
GPU1: NVIDIA GeForce RTX 3090 
Memory: 3042MiB / 128667MiB





> And about the termination of vLLM module. It can be OOM error. Do you check your VRAM status?

This is our `config.yaml`:
```yaml
# This config YAML file does not contain any optimization.
node_lines:
- node_line_name: retrieve_node_line  # Arbitrary node line name
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision]
      top_k: 3
      modules:
        - module_type: vectordb
          embedding_model: huggingface_baai_bge_small
- node_line_name: post_retrieve_node_line  # Arbitrary node line name
  nodes:
    - node_type: prompt_maker
      strategy:
        metrics: [bleu, meteor, rouge]
      modules:
        - module_type: fstring
          prompt: "Read the passages and answer the given question. \n Question: {query} \n Passage: {retrieved_contents} \n Answer : "
    - node_type: generator
      strategy:
        metrics: [bleu, meteor, rouge]
      modules:
        - module_type: vllm
          llm: mistralai/Mistral-7B-Instruct-v0.2
```
We checked the VRAM status and it takes only 1GB for the embedding computation (it seems not possible to occur in OOM error).
