### ISSUE TITLE
I got semantic retrieval module running log when I don't use it.

### ISSUE THREAD

**Issue by bwook00** [Marker-Inc-Korea/AutoRAG#602]
I used only bm25 at retrieval node, but i got semantic retrieval module running log.

![image](https://github.com/user-attachments/assets/b47e4bef-9533-4fe8-86df-e05d42e19ee8)

used yaml file (upload only retrieve_node_line!)

```
node_lines:
  - node_line_name: retrieve_node_line
    nodes:
      - node_type: retrieval
        strategy:
          metrics: [ retrieval_f1 ]
        top_k: 5
        modules:
          - module_type: bm25
            bm25_tokenizer: [ ko_kiwi ]
      - node_type: passage_reranker
        strategy:
          metrics: [ retrieval_f1 ]
        top_k: 3
        modules:
          - module_type: koreranker
```
