### ISSUE TITLE
[BUG] Bug at casting of retrieva_gt in retrieval run.py

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#773]
**Describe the bug**
There are strange code at the retrieval run.py

```python
retrieval_gt = qa_df["retrieval_gt"].tolist()
retrieval_gt = [
		[
			[str(uuid) for uuid in sub_array] if sub_array.size > 0 else []
			for sub_array in inner_array
		]
		for inner_array in retrieval_gt
	]
```

In here, the `sub_array.size` will be problem because of the `sub_array` can be string or something else. Especially, it is not working for list.

**To Reproduce**
Maybe use list of list retrieval_gt as retrieval_gt columns.

**Expected behavior**
It will not work when sub_array is string or list.

**Full Error log**
![image](https://github.com/user-attachments/assets/aabfe789-ba3e-447b-ad35-413270b48a8b)

**Code that bug is happened**

```yaml
node_lines:
- node_line_name: retrieve_node_line  # Set Node Line (Arbitrary Name)
  nodes:
    - node_type: retrieval  # Set Retrieval Node
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_ndcg, retrieval_mrr]  # Set Retrieval Metrics
      top_k: 3
      modules:
        - module_type: vectordb
          embedding_model: openai
        - module_type: bm25
        - module_type: hybrid_rrf
          weight_range: (4,80)
- node_line_name: post_retrieve_node_line  # Set Node Line (Arbitrary Name)
  nodes:
    - node_type: prompt_maker  # Set Prompt Maker Node
      strategy:
        metrics:   # Set Generation Metrics
          - metric_name: meteor
          - metric_name: rouge
          - metric_name: sem_score
            embedding_model: openai
      modules:
        - module_type: fstring
          prompt: "Read the passages and answer the given question. \n Question: {query} \n Passage: {retrieved_contents} \n Answer : "
    - node_type: generator  # Set Generator Node
      strategy:
        metrics:  # Set Generation Metrics
          - metric_name: meteor
          - metric_name: rouge
          - metric_name: sem_score
            embedding_model: openai
      modules:
        - module_type: openai_llm
          llm: gpt-4o-mini
          batch: 16
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS]
 - Python version [e.g. 3.10]

**Additional context**
