### ISSUE TITLE
[BUG] Cannot get start_end_idx from the langchain_chunk konlpy splitter

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#781]
**Describe the bug**
I used chunk.yaml file like below

```yaml
  - module_type: langchain_chunk
    chunk_method: konlpy
    chunk_size: 512
    chunk_overlap: 48
```

And I got no start_end_idx on the result corpus.parquet file.

![image](https://github.com/user-attachments/assets/61573de5-6ae0-4cf3-a927-c7ac700c50bd)

**To Reproduce**
Use this 5.parquet. 
I can’t upload parquet file in the github issue OMG

**Expected behavior**
It is missing start_end_idx… It is crucial.

**Full Error log**
If applicable, add full error log to help explain your problem.

**Code that bug is happened**
If applicable, add the code that bug is happened.
(Especially, your AutoRAG YAML file or python codes that you wrote)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS]
 - Python version [e.g. 3.10]

**Additional context**
