### ISSUE TITLE
[Feature Request] Add Nvidia Nim LLM

### ISSUE THREAD

**Issue by bwook00** [Marker-Inc-Korea/AutoRAG#926]

**Comment by bwook00** [comment]
We can use Nvidia Nim LLM to use LlamaIndex LLM's OpenAI LIke !

Here is the example YAML file to use `nvidia/llama-3.1-nemotron-70b-instruct` model.

```
nodes:
  - node_line_name: node_line_1
    nodes:
      - node_type: generator
        modules:
          - module_type: llama_index_llm
            llm: openailike
            model: nvidia/llama-3.1-nemotron-70b-instruct
            api_base: https://integrate.api.nvidia.com/v1
            api_key: your_api_key
```
