### ISSUE TITLE
[BUG] Unexpected Open API Requests Triggered Under Inactive Conditions

### ISSUE THREAD

**Issue by wisaaco** [Marker-Inc-Korea/AutoRAG#948]
**Describe the bug**
API calls to OpenAI occur despite having multiple modules configured to operate locally without OpenAI access.

This occurs in `post_retrieve_node_line` within `prompt_maker` when there are multiple instances of `module_type`, such as `fstrings`, during the Validation phase.

**To Reproduce**
Part of the config.yml
```
(...)
- node_line_name: post_retrieve_node_line  # Arbitrary node line name
  nodes:
    - node_type: prompt_maker
      strategy:
        metrics: [ meteor, rouge, bert_score ]
      modules:
          # - module_type: fstring
          #   prompt: "Read the passages and answer the given question. \n Question: {query} \n Passage: {retrieved_contents} \n Answer : "
         - module_type: fstring
           prompt: ["Tell me something about the question: {query} \n\n {retrieved_contents}",
                    "Question: {query} \n Something to read: {retrieved_contents} \n What's your answer?"]
        
      generator_modules:
          - module_type: llama_index_llm
            llm: ollama
            model: gemma2:27b
(...)
````

I get the logs:
```
INFO     [_client.py:1786] >> HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"                                _client.py:1786
	                    INFO     [_base_client.py:1661] >> Retrying request to /chat/completions in 0.421052 seconds                                                           _base_client.py:1661
	                    INFO     [_client.py:1786] >> HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"  
```

Swapping the comments between the module_types allows the validation to pass successfully.

Thanks

**Comment by wisaaco** [comment]
My mistake. I need to put the `generator_module` inside the strategy:
```yaml
      strategy:
        metrics: [ meteor, rouge ]
        generator_modules:
          - module_type: llama_index_llm
            llm: ollama
            model: gemma2:27b
            batch: 1
            temperature: 1.0
            request_timeout: 300 
```
